export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";
export const CHANGE_FAVORITE_STATUS = "CHANGE_FAVORITE_STATUS";
export const RESET_ALL_STATUS = "RESET_ALL_STATUS";